name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git diff --patch-with-raw --raw --minimal --compact-summary origin/${{ github.base_ref }}..HEAD > diff.txt
          echo " ## Pull Request Diff ```diff  $(cat diff.txt)```" >> $GITHUB_STEP_SUMMARY
