# Documentation: https://docs.github.com/ru/actions
# Workflow for updating PR description with AI summary
name: AI Summary for Pull Request
run-name: ${{ github.actor }} updating summary 📔
on: [pull_request]
jobs:
  Update-PR-Description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get the diff
        id: diff
        run: |
          git diff --patch-with-raw --raw --minimal --compact-summary origin/master HEAD > diff.txt
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Generate summary
        id: summary
        run: |
          echo  "`cat diff.txt`"
          export summary_input="`cat diff.txt | base64`"
          bundle exec rake summary_base64 > summary.txt
          echo $(cat summary.txt)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Update PR Description
        uses: nefrob/pr-description@v1.1.2
        if: steps.summary.outcome == 'success' && steps.diff.outcome == 'success'
        with:
          content: summary.txt
          contentIsFilePath: true
          regexFlags: s
          token: ${{ secrets.GITHUB_TOKEN }}
