name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git diff origin/${{ github.base_ref }}..HEAD > diff.txt
          echo "🔍 The changes in the pull request are: $(cat diff.txt)"
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "📦 The ${{ github.base_ref }} base refrence and ${{ github.head_ref }}"
      - run: echo "🍏 This job's status is ${{ job.status }}."
